version: '3.1'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    expose:
      - 5432
